Vagrant.configure("2") do |config|
  (0..2).each do |i|
    config.vm.define "cka-node-#{i}" do |cka|
      cka.vm.box = "generic/ubuntu1804"
      cka.vm.network "public_network", bridge: "Realtek PCIe GBE Family Controller", ip: "192.168.25.6#{i}"
      cka.vm.provision "shell", path: "script-node-#{i}.sh"
    end  
  end
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end